# project config
project:
  filesource:  # 文件源配置，如果 generator.from-file 为 false，忽略此配置
    # 指定设计文档的路径，目前仅支持 docx 格式
    doc-file: 'E:\example\helloworld\doc\db\数据库设计-演示.docx'
  datasource:  # 数据库配置，如果 generator.from-file 为 true，忽略此配置，目前仅支持 mysql
    host: 47.101.163.238
    port: 3999
    database: forsrc
    username: 'dbuser'
    password: 'G4f#I&Kg^6Hc'
  generator:
    from-file: true  # 是否从文档生成，true从文档生成。false 从数据库生成，如果是从数据库生成，需要配置 datasource 数据源。默认为 false
    application:
      # 应用程序的 key，forsrc 根据这个 key 区分不同应用程序，可参照官网进行配置
      app-key: 'java:springboot:webapp:vue:base'
      version: 1.0  # 分支版本，0 最新版本
    database:
      type: mysql  # 生成数据库的类型，目前支持：mysql，postgresql，greenplum
      sql-version: 1.0
    filter:
      table:
        # 指定仅生成以表头部开头的表，"!"开头表示选择不以这个开头的表，与其它条件为 and 关系，不能设置多个。
        name-prefix: ''
        # 指定表名包含什么内容，仅字母、数字或下划线，与其它条件为 and 关系，不能设置多个。
        name-contain: ''
        # 正则表达式指定表名，可以指定多个表达式，逗号分隔，与其它条件为 and 关系。
        table-regex: ''
        # 指定哪些表，多个表用英文逗号分隔，空或*为全部，与其它条件为 and 关系。
        tables: ''
    project:
      name: 'example'  # 项目名称
      title: 'springboot 样例'  # 项目标题
      src-pack: 'com.example'  # 包的名称，所有生成的程序都在这个包下面
    output:
      # 是否生成 src 部分
      generator-src: true
      # 是否生成 web 部分
      generator-web: true
      # 是否生成 sql 语句
      generator-sql: true
      # src 的保存路径
      save-src-path: 'E:\example\helloworld\source\app\src'
      # web 的保存路径
      save-web-path: 'E:\example\helloworld\source\web\src'
      # sql 的保存路径
      save-sql-path: 'E:\example\helloworld\doc\db\sql'
      # 保护的文件或路径，绝对路径，区分大小写，支持 ? 和 * 通配符。如果不存在，写入文件或文件夹；如果已经存在，跳过文件或文件夹。
      protected-file-path:
        - '${project.generator.output.save-src-path}\main\resources\application*'