# project config
project:
  filesource:  # 文件源配置，如果 generator.from-file 为 false，忽略此配置
    # 指定设计文档的路径，目前仅支持 docx 格式
    doc-file: 'E:\example\helloworld\doc\db\数据库设计-演示.docx'
  datasource:  # 数据库配置，如果 generator.from-file 为 true，忽略此配置，目前仅支持 mysql
    host: localhost
    port: 3306
    database: example
    username: 'root'
    password: 'root'
  generator:
    from-file: true  # 是否从文档生成，true从文档生成。false 从数据库生成，如果是从数据库生成，需要配置 datasource 数据源。默认为 false
    application:
      # 应用程序的 key，forsrc 根据这个 key 区分不同应用程序，可参照官网进行配置
      app-key: 'java:springboot:webapp:vue:base'
      version: 1.0  # 分支版本，0 最新版本
    database:
      type: 'mysql'  # 生成数据库的类型，目前支持：mysql，postgresql，greenplum
      sql-version: 1.0
    document:
      add-table-title: false # 生成数据库文档的表是否添加标题，默认不添加。如果为 true，生成每个表的第一行为标题; 否则，只在文档起始位置加一个标题。
    filter:
      table:
        # 指定仅生成以表头部开头的表，"!"开头表示选择不以这个开头的表，与其它条件为 and 关系，不能设置多个。
        name-prefix: ''
        # 指定表名包含什么内容，仅字母、数字或下划线，与其它条件为 and 关系，不能设置多个。
        name-contain: ''
        # 正则表达式指定表名，可以指定多个表达式，逗号分隔，与其它条件为 and 关系。需要使用双引号转义。
        table-regex: ""
        # 指定哪些表，多个表用英文逗号分隔，空或*为全部，与其它条件为 and 关系。
        tables: ''
    option:
      database:
        # 是否去掉表头，true 去掉表头作为tableBody，false 不去掉，默认为 false，如 table_user 表，去掉后类名为 User，不去掉为 TableUser
        rid-table-prefix: true
    project:
      name: 'example'  # 项目名称，必须以字母开头，由字母、数字、下划线、中划线组成。
      title: 'springboot 样例'  # 项目标题
      app-pack: 'com.example'  # app 包的名称，生成 app 的源程序都在这个包下面
      auto-deploy: true
    output:
      # 是否生成 app 部分
      generator-app: true
      # 是否生成 web 部分
      generator-web: true
      # 是否生成 sql 语句
      generator-sql: true
      # 是否生成 doc
      generator-doc: true
      # app 的保存路径
      save-app-path: 'E:\example\helloworld\source\app\src'
      # web 的保存路径
      save-web-path: 'E:\example\helloworld\source\web\src'
      # sql 的保存路径
      save-sql-path: 'E:\example\helloworld\doc\db\sql'
      # doc 的保存路径
      save-doc-path: 'E:\example\helloworld\doc\db'
      # 保护的文件或路径，绝对路径，区分大小写，支持 ? 和 * 通配符。如果不存在，写入文件或文件夹；如果已经存在，跳过文件或文件夹。
      protected-file-path:
        - '${project.generator.output.save-app-path}\main\resources\application*'
#        - '${project.generator.output.save-app-path}\main\java\com\project\local\app'
#        - '${project.generator.output.save-app-path}\main\java\com\project\local\common\constant\EnumCode.java'
#        - '${project.generator.output.save-app-path}\main\java\com\project\local\security\service'
#        - '${project.generator.output.save-app-path}\main\java\com\project\local\business\user'
#        - '${project.generator.output.save-app-path}\main\java\com\project\local\common\response'
#        - '${project.generator.output.save-app-path}\main\java\com\project\local\common\spring\base'
#        - '${project.generator.output.save-app-path}\main\java\com\project\local\mvc\event'