#
project:
  filesource:  # 文件源配置，如果 generator.from-file 为 false，忽略此配置
    # 指定设计文档的路径，目前仅支持 docx 格式
    # aatp
    doc-file: 'E:\prog\java\2021\amygo\project\aatp\doc\db\数据库设计-20211213.docx'
  datasource:  # 数据库配置，如果 generator.from-file 为 true，忽略此配置，目前仅支持 mysql
    host: 10.21.0.15
    port: 5533
    database: forsrc
    username: 'dbuser'
    password: 'dpG!0U3g#6Hz'
  generator:
    from-file: true  # 是否从文档生成，true从文档生成。false 从数据库生成，如果是从数据库生成，需要配置 datasource 数据源。默认为 false
    application:
      # 应用程序的 key，forsrc 根据这个 key 区分不同应用程序，可参照官网进行配置
      app-key: 'java:springboot:webapp:vue:base'
      version: 1.0  # 分支版本，0 最新版本
    database:
      type: postgresql  # 生成数据库的类型，目前支持：mysql，postgresql，greenplum
      sql-version: 1.0
    filter:
      table:
        # 指定仅生成以表头部开头的表，!开头表示不以这个开头的，与其它条件为 and 关系，不能设置多个。
        name-prefix: ''
        # 指定表名包含什么内容，仅字母、数字或下划线，与其它条件为 and 关系，不能设置多个。
        name-contain: ''
        # 正则表达式指定表名，可以指定多个表达式，逗号分隔，与其它条件为 and 关系。
        table-regex: ''
        # 指定哪些表，多个表用英文逗号分隔，空或*为全部，与其它条件为 and 关系。
        tables: ''
    #      tables: 'schemata, tables, columns, table_constraints, statistics'
    project:
      name: 'aatp'   # 项目名称
      title: 'Amygo标注管理平台' # 项目标题
      # 包的名称，所有生成的程序都在这个包下面
      src-pack: 'com.project.amygo.aatp.site'
    output:
      # 是否生成 src 部分
      generator-src: true
      # 是否生成 web 部分
      generator-web: true
      # 是否生成 sql 语句
      generator-sql: true
      # src 的保存路径
      save-src-path: 'E:\prog\java\2021\amygo\project\aatp\prog\aatp-site\source\src'
      # web 的保存路径
      save-web-path: 'E:\prog\java\2021\amygo\project\aatp\web\vue\src'
      # sql 的保存路径
      save-sql-path: 'E:\prog\java\2021\amygo\project\aatp\doc\db\sql'
      # 保护的文件或路径，绝对路径，区分大小写，支持?和*通配符。如果不存在，写入文件或文件夹；如果已经存在，跳过文件或文件夹，不覆盖。
      protected-file-path:
        - '${forsrc.generator.output.save-src-path}\main\resources\application*'
        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\aatp\site\common\constant\EnumCode.java'
        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\aatp\site\common\exception'
        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\aatp\site\common\response'
        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\aatp\site\common\spring\base'
        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\aatp\site\security\service'
        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\aatp\site\mvc\event'