#
application:
  port: 8010
  name: client

log:
  level:
    root: info
    dao: debug
  file: /home/dpi/log/dpi.log

#websocket:
#  enable: true
#  message-timeout: 30
#  login-timeout: 30

#redis:
#  cluster-hosts: '47.103.65.29:6379:Ji3$k&6&q5!L'
#  max-total: 200
#  max-idle: 100
#  min-idle: 0
#  test-borrow: false
#  test-return: false
#  # second
#  ttl: 1800
#  key-head: core-

forsrc:
  # 授权部分，如果是企业，配置企业 appid 和 secret，如果是个人，配置账号 username 和 password。
  authorization:
    # 用户名
    username: forsrc
    # 秘钥，不是密码，注册后会自动生成秘钥
    secret: forsrc
  # 文件源配置，如果 generator.from-file 为 false，忽略此配置
  filesource:
    # 指定设计文档的路径，目前仅支持 docx 格式
    # aatp
    doc-file: 'E:\prog\java\2021\amygo\project\aatp\doc\db\数据库设计-20211213.docx'
#    # 文档中的表是否有标题头(第一行)，true 有标题头(标题头不计入字段，将被忽略)，false 无标题头
    table-has-header: false
    # 设置是否检查关键字，设置为true将检查数据库关键字，java关键字和内部关键字不管是否设置都会检查。如果不检查生成的源码有可能出现错误。
    check-reserve-word: false
    # 文档中字段属性所在的列，从 1 开始，-1 表示无此定义，前三个属性title, name, type必须定义
    field-property-column:
      # 字段标题
      title: 1
      # 字段名称，参数格式(字母开头，字母，数字或下划线组成)
      name: 2
      # 字段数据库类型
      type: 3
      # 是否非空，非空字段设置为'是'，可空字段不用填
      notnull: 4
      # 缺省值
      default-value: 5
      # 字段说明，字段配置均在此列
      description: 6
  # 数据库配置，如果 generator.from-file 为 true，忽略此配置
  datasource:
    # 数据库类型，目前仅支持 mysql
    type: mysql
    host: 124.70.204.115
    port: 3999
    database: dpi_gp
    username: 'dbuser'
    password: 'G4f#I&Kg^6Hc'
  generator:
    # 是否从文档生成，true从文档生成。false 从数据库生成，如果是从数据库生成，需要配置 datasource 数据源。默认为 false
    from-file: true
    application:
      app-key: 'java:springboot:webapp:vue:base'
      version: 1.0  # 分支版本，0 最新版本
    database:
      type: postgresql  # 生成数据库的类型，目前支持：mysql，postgresql，greenplum
      sql-version: 1.0
      sql-comment: true  # sql 语句是否添加注释，true添加。
    filter:
      table:
        # 指定仅生成以表头部开头的表，!开头表示不以这个开头的，与其它条件为 and 关系，不能设置多个。
        #      name-prefix: 't_'
        name-prefix: ''
        # 指定表名包含什么内容，仅字母、数字或下划线，与其它条件为 and 关系，不能设置多个。
        name-contain: ''
        # 正则表达式指定表名，可以指定多个表达式，逗号分隔，与其它条件为 and 关系。
        table-regex: ""
        # 指定哪些表，多个表用英文逗号分隔，空或*为全部，与其它条件为 and 关系
        tables: 'auth_user, auth_company, t_province, t_city, t_file_upload, t_algo_task, engine_project, engine_task, engine_data'
    #      tables: 'schemata, tables, columns, table_constraints, statistics'
    option:
      database:
        # 是否去掉表头，true 去掉表头作为tableBody，false 不去掉，默认为 false，如 t_user 表，去掉后类名为 User，不去掉为 TUser
        rid-table-prefix: false
        # 缺省查询显示字段总个数，默认10，可以在外键字段中配置selectFieldNum来设置外键表中显示出的字段数，0自动计算，-1全部不显示
        # 此值目前在服务器端设置，客户端设置无效
        select-field-num: 20
    project:
      name: 'aatp'   # 项目名称
      title: 'Amygo标注管理平台' # 项目标题
      # 包的名称，所有生成的程序都在这个包下面
      src-pack: 'com.project.amygo.aatp.algo'
    output:
      # 如果存在时是否覆盖，true覆盖，false不覆盖
      rewrite-on-exist: true
      # 是否生成 src 部分
      generator-src: true
      # 是否生成 web 部分
      generator-web: false
      # 是否生成 sql 语句
      generator-sql: false
      # src 的保存路径
      save-src-path: 'E:\prog\java\2021\amygo\project\aatp\prog\aatp-algo\source\src'
      # web 的保存路径
      save-web-path: 'E:/prog/java/2021/amigo/datalab/aatp/aatp-2d/prog/js/vue/src'
      # sql 的保存路径
      save-sql-path: 'E:/prog/java/2021/amigo/datalab/aatp/aatp-2d/doc/develop/db/sql'
      # 保护的文件或路径，绝对路径，区分大小写，支持?和*通配符。如果不存在，写入文件或文件夹；如果已经存在，跳过文件或文件夹，不覆盖。
      protected-file-path:
        - '${forsrc.generator.output.save-src-path}\main\resources\application*'
        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\aatp\algo\common\constant\EnumCode.java'
        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\aatp\algo\security\service'
        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\aatp\algo\common\spring\base'
#        - '${forsrc.generator.output.save-src-path}\main\java\com\project\amygo\algo\site\mvc\handle'